name: CI

on: [push]

jobs:
  build:
    name: shalzz/zola-deploy-action
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Zola Deploy to Pages
        uses: shalzz/zola-deploy-action@v0.9.2
        env:
          PAGES_BRANCH: gh-pages
