name: CI

on: [push]

jobs:
  build:
    name: shalzz/zola-deploy-action
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Zola Deploy to Pages
      uses: shalzz/zola-deploy-action@v0.9.2
      env:
        PAGES_BRANCH: gh-pages
        TOKEN: ${{ secrets.LP_DEPLOY_KEY }}
